name: Build artifacts
on:
  push:
    tags:
      - '*'
jobs:
  xar:
    name: Build the exist user from env xar package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          # fetch all history to include latest tag for the git revision info
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Build with Ant
        run: ant clean xar
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/*.xar